#  ____    _       _   _   _____    ___    _   _   ____     ____   _   _   _____   ____    _   _   _       _____   ____
# |  _ \  | |     | | | | |_   _|  / _ \  | \ | | / ___|   / ___| | | | | | ____| |  _ \  | | | | | |     | ____| |  _ \
# | |_) | | |     | | | |   | |   | | | | |  \| | \___ \  | |     | |_| | |  _|   | | | | | | | | | |     |  _|   | |_) |
# |  __/  | |___  | |_| |   | |   | |_| | | |\  |  ___) | | |___  |  _  | | |___  | |_| | | |_| | | |___  | |___  |  _ <
# |_|     |_____|  \___/    |_|    \___/  |_| \_| |____/   \____| |_| |_| |_____| |____/   \___/  |_____| |_____| |_| \_\
# Created by BrandonGouw#1781

messages:
  reload-message: '&a&l[!] &aYou have reloaded the config'
  help:
    - '&6&lPLUTON &e&lSCHEDULER | &7Made by BrandonGouw'
    - '&6/plutonscheduler reload &eReloads the config'
    - '&6/plutonscheduler help &eShows this menu'